export const SORT_TYPES = {
  DAMAGE: 'DAMAGE',
  HEAL: 'HEAL',
  BUFF: 'BUFF',
  DEBUFF: 'DEBUFF',
  MOVEMENT: 'MOVEMENT',
  MOVEMENT_DAMAGE: 'MOVEMENT_DAMAGE',
  DOT_DAMAGE: 'DOT_DAMAGE',
  AREA_DAMAGE: 'AREA_DAMAGE',
  UTILITY: 'UTILITY',
};
